blossom-ui/blossom-ui-web/src/main/java/com/blossomproject/ui/web/system/dashboard/DashboardController.java
package com.blossomproject.ui.web.system.dashboard;

import com.google.common.collect.Lists;
import com.blossomproject.ui.menu.OpenedMenu;
import com.blossomproject.ui.stereotype.BlossomController;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Statistic;
import java.util.List;
import java.util.stream.Collectors;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.actuate.health.Health;
import org.springframework.boot.actuate.health.HealthEndpoint;
import org.springframework.boot.actuate.metrics.MetricsEndpoint;
import org.springframework.boot.actuate.metrics.MetricsEndpoint.MetricResponse;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

/**
 * Created by Maël Gargadennnec on 04/05/2017.
 */
@BlossomController
@RequestMapping("/system/dashboard")
@OpenedMenu("dashboard")
@PreAuthorize("hasAuthority('system:dashboard:manager')")
public class DashboardController {

  private final static Logger logger = LoggerFactory.getLogger(DashboardController.class);

  private final HealthEndpoint healthEndpoint;
  private final MetricsEndpoint metricsEndpoint;

  @Autowired
  private MeterRegistry registry;

  public DashboardController(HealthEndpoint healthEndpoint, MetricsEndpoint metricsEndpoint) {
    this.healthEndpoint = healthEndpoint;
    this.metricsEndpoint = metricsEndpoint;
  }

  @GetMapping
  public ModelAndView dashboard() {
    return new ModelAndView("blossom/system/dashboard/dashboard");
  }

  @GetMapping("/status")
  public ModelAndView status(Model model) {
    Health health = healthEndpoint.health();
    model.addAttribute("health", health);
    model.addAttribute("uptime",
      1000 * metricsEndpoint.metric("process.uptime", null).getMeasurements().get(0).getValue());
    return new ModelAndView("blossom/system/dashboard/panel/status", model.asMap());
  }

  @GetMapping("/memory")
  public ModelAndView memory() {
    JVMMemoryUsage memoryUsage = new JVMMemoryUsage(
      metric("jvm.memory.max").longValue(),
      metric("jvm.memory.max").longValue() - metric("jvm.memory.used").longValue());
    MemoryUsage heap = new MemoryUsage(
      0,
      metric("jvm.memory.used", Lists.newArrayList("area:heap")).longValue(),
      metric("jvm.memory.committed", Lists.newArrayList("area:heap")).longValue(),
      metric("jvm.memory.max", Lists.newArrayList("area:heap")).longValue());
    MemoryUsage nonheap = new MemoryUsage(
      0,
      metric("jvm.memory.used", Lists.newArrayList("area:nonheap")).longValue(),
      metric("jvm.memory.committed", Lists.newArrayList("area:nonheap")).longValue(),
      metric("jvm.memory.max", Lists.newArrayList("area:nonheap")).longValue());

    MemoryMetrics memoryMetrics = new MemoryMetrics(memoryUsage, heap, nonheap);

    return new ModelAndView("blossom/system/dashboard/panel/memory", "memory", memoryMetrics);
  }

  @GetMapping("/jvm")
  public ModelAndView jvm() {
    ClassMetrics classes = new ClassMetrics(
      metric("jvm.classes.loaded").intValue(),
      metric("jvm.classes.unloaded").intValue());

    GCMetrics gcs = new GCMetrics(
      metricsEndpoint.metric("jvm.gc.pause", null).getAvailableTags()
        .stream()
        .filter(t -> t.getTag().equals("action")).flatMap(action -> action.getValues().stream())
        .map(value -> {
          MetricResponse metric = metricsEndpoint
            .metric("jvm.gc.pause", Lists.newArrayList("action:" + value));
          return new GCMetric(
            value,
            metric.getMeasurements().stream().filter(m -> m.getStatistic() == Statistic.COUNT)
              .findFirst().get().getValue().longValue(),
            metric.getMeasurements().stream().filter(m -> m.getStatistic() == Statistic.TOTAL_TIME)
              .findFirst().get().getValue().doubleValue()
          );
        })
        .collect(Collectors.toList())
    );

    ThreadMetrics threads = new ThreadMetrics(
      metric("jvm.threads.live").intValue(),
      metric("jvm.threads.peak").intValue(),
      metric("jvm.threads.daemon").intValue());
    ProcessorMetrics processors = new ProcessorMetrics(
      metric("system.cpu.count").intValue()
    );

    JVMMetrics jvmMetrics = new JVMMetrics(classes, gcs, threads, processors);
    return new ModelAndView("blossom/system/dashboard/panel/jvm", "jvm", jvmMetrics);
  }

  @GetMapping("/charts")
  public ModelAndView requests() {
    return new ModelAndView("blossom/system/dashboard/panel/charts");
  }

  private Double metric(String name) {
    return this.metricsEndpoint.metric(name, null).getMeasurements().get(0).getValue();
  }

  private Double metric(String name, List<String> tags) {
    return this.metricsEndpoint.metric(name, tags).getMeasurements().get(0).getValue();
  }

  public static String humanReadableByteCount(long bytes, boolean si) {
    int unit = si ? 1000 : 1024;
    if (bytes < unit) {
      return bytes + " B";
    }
    int exp = (int) (Math.log(bytes) / Math.log(unit));
    String pre = (si ? "kMGTPE" : "KMGTPE").charAt(exp - 1) + (si ? "" : "i");
    return String.format("%.1f %sB", bytes / Math.pow(unit, exp), pre);
  }

  public class MemoryMetrics {

    private final JVMMemoryUsage jvm;
    private final MemoryUsage heap;
    private final MemoryUsage nonheap;

    public MemoryMetrics(JVMMemoryUsage jvm, MemoryUsage heap, MemoryUsage nonheap) {
      this.jvm = jvm;
      this.heap = heap;
      this.nonheap = nonheap;
    }

    public JVMMemoryUsage getJvm() {
      return jvm;
    }

    public MemoryUsage getHeap() {
      return heap;
    }

    public MemoryUsage getNonheap() {
      return nonheap;
    }

  }


  public static class JVMMemoryUsage {

    private final long total;
    private final long free;

    public JVMMemoryUsage(long total, long free) {
      this.total = total;
      this.free = free;
    }

    public String getTotal() {
      return humanReadableByteCount(total, true);
    }

    public String getFree() {
      return humanReadableByteCount(free, true);
    }

    public String getUsed() {
      return humanReadableByteCount(total - free, true);
    }

    public float getPercentage() {
      return ((float) total - (float) free) / (float) total * 100;
    }
  }

  public static class MemoryUsage {

    private final long init;
    private final long used;
    private final long committed;
    private final long max;

    public MemoryUsage(long init, long used, long committed, long max) {
      this.init = init;
      this.used = used;
      this.committed = committed;
      this.max = max;
    }

    public String getInit() {
      return humanReadableByteCount(init, true);
    }

    public String getUsed() {
      return humanReadableByteCount(used, true);
    }

    public String getCommitted() {
      return humanReadableByteCount(committed, true);
    }

    public String getMax() {
      return humanReadableByteCount(max, true);
    }

    public float getPercentage() {
      return (float) used / (float) committed * 100;
    }
  }

  public class JVMMetrics {

    private final ClassMetrics classes;
    private final GCMetrics gcs;
    private final ThreadMetrics threads;
    private final ProcessorMetrics processors;

    public JVMMetrics(ClassMetrics classes, GCMetrics gcs, ThreadMetrics threads,
      ProcessorMetrics processors) {
      this.classes = classes;
      this.gcs = gcs;
      this.threads = threads;
      this.processors = processors;
    }

    public ClassMetrics getClasses() {
      return classes;
    }

    public GCMetrics getGcs() {
      return gcs;
    }

    public ThreadMetrics getThreads() {
      return threads;
    }

    public ProcessorMetrics getProcessors() {
      return processors;
    }

  }


  public static class ClassMetrics {

    private final long total;
    private final long loaded;
    private final long unloaded;

    public ClassMetrics(long loaded, long unloaded) {
      this.total = loaded + unloaded;
      this.loaded = loaded;
      this.unloaded = unloaded;
    }

    public long getTotal() {
      return total;
    }

    public long getLoaded() {
      return loaded;
    }

    public long getUnloaded() {
      return unloaded;
    }
  }

  public static class GCMetrics {

    private final List<GCMetric> types;

    public GCMetrics(List<GCMetric> types) {
      this.types = types;
    }

    public List<GCMetric> getTypes() {
      return types;
    }

  }

  public static class GCMetric {

    private final String name;
    private final long count;
    private final double time;

    public GCMetric(String name, long count, double time) {
      this.name = name;
      this.count = count;
      this.time = time;
    }

    public String getName() {
      return name;
    }

    public long getCount() {
      return count;
    }

    public double getTime() {
      return time;
    }
  }

  public static class ThreadMetrics {

    private final long live;
    private final long peak;
    private final long daemon;

    public ThreadMetrics(long live, long peak, long daemon) {
      this.live = live;
      this.peak = peak;
      this.daemon = daemon;
    }

    public long getLive() {
      return live;
    }

    public long getPeak() {
      return peak;
    }

    public long getDaemon() {
      return daemon;
    }
  }

  public static class ProcessorMetrics {

    private final int total;

    public ProcessorMetrics(int total) {
      this.total = total;
    }

    public int getTotal() {
      return total;
    }
  }
}

blossom-ui/blossom-ui-web/src/main/resources/templates/blossom/system/dashboard/panel/charts.ftl
<#import "/spring.ftl" as spring>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-content text-center" style="position: relative">
        <p>
          <a class="btn btn-primary btn-xs btn-rounded" data-toggle="period" data-period="PAST_WEEK"><@spring.message "dashboard.charts.period.PAST_WEEK"/></a>
          <a class="btn btn-default btn-xs btn-rounded" data-toggle="period" data-period="PAST_5_DAYS"><@spring.message "dashboard.charts.period.PAST_5_DAYS"/></a>
          <a class="btn btn-default btn-xs btn-rounded" data-toggle="period" data-period="PAST_3_DAYS"><@spring.message "dashboard.charts.period.PAST_3_DAYS"/></a>
          <a class="btn btn-default btn-xs btn-rounded" data-toggle="period" data-period="PAST_2_DAYS"><@spring.message "dashboard.charts.period.PAST_2_DAYS"/></a>
          <a class="btn btn-default btn-xs btn-rounded" data-toggle="period" data-period="YESTERDAY"><@spring.message "dashboard.charts.period.YESTERDAY"/></a>
          <a class="btn btn-default btn-xs btn-rounded" data-toggle="period" data-period="TODAY"><@spring.message "dashboard.charts.period.TODAY"/></a>
          <br/>
          <a class="btn btn-default btn-xs btn-rounded" data-toggle="period" data-period="PAST_24_HOURS"><@spring.message "dashboard.charts.period.PAST_24_HOURS"/></a>
          <a class="btn btn-default btn-xs btn-rounded" data-toggle="period" data-period="PAST_12_HOURS"><@spring.message "dashboard.charts.period.PAST_12_HOURS"/></a>
          <a class="btn btn-default btn-xs btn-rounded" data-toggle="period" data-period="PAST_6_HOURS"><@spring.message "dashboard.charts.period.PAST_6_HOURS"/></a>
          <a class="btn btn-default btn-xs btn-rounded" data-toggle="period" data-period="PAST_HOUR"><@spring.message "dashboard.charts.period.PAST_HOUR"/></a>
          <a class="btn btn-default btn-xs btn-rounded" data-toggle="period" data-period="PAST_30_MINUTES"><@spring.message "dashboard.charts.period.PAST_30_MINUTES"/></a>
          <a class="btn btn-default btn-xs btn-rounded" data-toggle="period" data-period="PAST_5_MINUTES"><@spring.message "dashboard.charts.period.PAST_5_MINUTES"/></a>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div id="requests" class="ibox float-e-margins">
      <div class="ibox-title">
        <h5><@spring.message "dashboard.charts.request"/></h5>
      </div>
      <div class="ibox-content" style="position: relative">
        <div class="sk-spinner sk-spinner-wave">
          <div class="sk-rect1"></div>
          <div class="sk-rect2"></div>
          <div class="sk-rect3"></div>
          <div class="sk-rect4"></div>
          <div class="sk-rect5"></div>
        </div>

        <div id="requests-area-chart" style="height: 200px;"></div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-4">
    <div id="response_status" class="ibox float-e-margins">
      <div class="ibox-title">
        <h5><@spring.message "dashboard.charts.response_status"/></h5>
      </div>
      <div class="ibox-content">
        <div class="sk-spinner sk-spinner-wave">
          <div class="sk-rect1"></div>
          <div class="sk-rect2"></div>
          <div class="sk-rect3"></div>
          <div class="sk-rect4"></div>
          <div class="sk-rect5"></div>
        </div>
        <div id="response-status-donut-chart" style="height: 200px;"></div>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div id="response_time" class="ibox float-e-margins">
      <div class="ibox-title">
        <h5><@spring.message "dashboard.charts.response_time"/></h5>
      </div>
      <div class="ibox-content">
        <div class="sk-spinner sk-spinner-wave">
          <div class="sk-rect1"></div>
          <div class="sk-rect2"></div>
          <div class="sk-rect3"></div>
          <div class="sk-rect4"></div>
          <div class="sk-rect5"></div>
        </div>
        <div id="response-time-bar-chart" style="height: 200px;"></div>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div id="response_content_type" class="ibox float-e-margins">
      <div class="ibox-title">
        <h5><@spring.message "dashboard.charts.response_content_type"/></h5>
      </div>
      <div class="ibox-content">
        <div class="sk-spinner sk-spinner-wave">
          <div class="sk-rect1"></div>
          <div class="sk-rect2"></div>
          <div class="sk-rect3"></div>
          <div class="sk-rect4"></div>
          <div class="sk-rect5"></div>
        </div>
        <div id="response-content-type-donut-chart" style="height: 200px;"></div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <div id="top_uris" class="ibox float-e-margins">
      <div class="ibox-title">
        <h5><@spring.message "dashboard.charts.top_uris"/></h5>
      </div>
      <div class="ibox-content">
        <div class="sk-spinner sk-spinner-wave">
          <div class="sk-rect1"></div>
          <div class="sk-rect2"></div>
          <div class="sk-rect3"></div>
          <div class="sk-rect4"></div>
          <div class="sk-rect5"></div>
        </div>
        <table class="table table-responsive table-stripped">
          <thead>
          <tr>
            <th><@spring.message "dashboard.charts.top_uris.uri"/></th>
            <th><@spring.message "dashboard.charts.top_uris.count"/></th>
          </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div id="flop_uris" class="ibox float-e-margins">
      <div class="ibox-title">
        <h5><@spring.message "dashboard.charts.flop_uris"/></h5>
      </div>
      <div class="ibox-content">
        <div class="sk-spinner sk-spinner-wave">
          <div class="sk-rect1"></div>
          <div class="sk-rect2"></div>
          <div class="sk-rect3"></div>
          <div class="sk-rect4"></div>
          <div class="sk-rect5"></div>
        </div>

        <table class="table table-responsive table-stripped">
          <thead>
          <tr>
            <th><@spring.message "dashboard.charts.flop_uris.uri"/></th>
            <th><@spring.message "dashboard.charts.flop_uris.count"/></th>
          </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


<script>
  $(document).ready(function () {
      var requestHistogramChart = Morris.Area({
        element: 'requests-area-chart',
        data: [],
        xkey: 'period',
        pointSize: 3,
        hideHover: 'auto',
        resize: true,
        lineWidth: 2,
        pointSize: 1
      });

      var responseTimeBarChart = Morris.Bar({
        element: 'response-time-bar-chart',
        data: [{label:'100', value:1}],
        xkey: 'time',
        ykeys: ['count'],
        labels: ['Count'],
        hideHover: 'auto',
        resize: true,
        barColors: ['<@spring.theme "_primary"/>']
      });

      var responseStatusDonutChart = Morris.Donut({
        element: 'response-status-donut-chart',
        data: [{label: '200', value: 1}],
        resize: true,
        colors: ['<@spring.theme "_primary"/>'],
      });


      var responseContentTypeDonutChart = Morris.Donut({
        element: 'response-content-type-donut-chart',
        data: [{label: 'text/html', value: 1}],
        resize: true,
        colors: ['<@spring.theme "_primary"/>'],
      });


      var updateRequests = function (data) {
        var chartData = [];
        var keys = [];

        var histogrammBars = data.aggregations.request_histogram.buckets;
        $.each(histogrammBars, function (index, histogrammBar) {
          var item = {period: histogrammBar.key};
          var methods = histogrammBar.methods.buckets;
          $.each(methods, function (index2, method) {
            item[method.key] = method.doc_count;
            if (keys.indexOf(method.key) == -1) {
              keys.push(method.key)
            }
          });
          chartData.push(item);
        });


        if (chartData.length > 0) {
          var rainbow = new Rainbow();
          rainbow.setSpectrumByArray(['<@spring.theme "_primary"/>', '#d3d3d3']);
          rainbow.setNumberRange(0, keys.length);
          var colors = [];
          $.each(keys, function (index, key) {
            colors.push('#' + rainbow.colourAt(index));
          });

          requestHistogramChart.options.lineColors = colors;
          requestHistogramChart.options.labels = keys;
          requestHistogramChart.options.ykeys = keys;
          requestHistogramChart.setData(chartData);
        }else{
          requestHistogramChart.setData(chartData);
        }

      };

      var updateResponseTime = function (data) {
        var chartData = [];
        var responseTimeBars = data.aggregations.response_time_histogram.buckets;
        $.each(responseTimeBars, function (index, responseTimeBar) {
          var item = {time: responseTimeBar.key, count: responseTimeBar.doc_count};
          chartData.push(item);
        });

        responseTimeBarChart.setData(chartData);

      };

      var updateResponseStatus = function (data) {
        var chartData = [];
        var responseStatuses = data.aggregations.response_status_stats.buckets;
        $.each(responseStatuses, function (index, responseStatus) {
          var key = responseStatus.key;
          var item = {label: key, value: responseStatus.doc_count};
          chartData.push(item);
        });
        if (chartData.length > 0) {
          var rainbow = new Rainbow();
          rainbow.setSpectrumByArray(['<@spring.theme "_primary"/>', '#d3d3d3']);
          rainbow.setNumberRange(0, chartData.length);
          var colors = [];
          $.each(chartData, function (index) {
            colors.push('#' + rainbow.colourAt(index));
          });

          responseStatusDonutChart.options.colors = colors;
          responseStatusDonutChart.setData(chartData);
        }
        else {
          responseStatusDonutChart.setData([{label: 'No data', value: 0}]);
        }
      };


      var updateResponseContentType = function (data) {
        var chartData = [];
        var responseContentTypes = data.aggregations.response_content_type_stats.buckets;
        $.each(responseContentTypes, function (index, responseContentType) {
          var key = responseContentType.key.indexOf(';') != -1 ? responseContentType.key.split(';')[0] : responseContentType.key;
          var item = {label: key, value: responseContentType.doc_count};
          chartData.push(item);
        });
        if (chartData.length > 0) {
          var rainbow = new Rainbow();
          rainbow.setSpectrumByArray(['<@spring.theme "_primary"/>', '#d3d3d3']);
          rainbow.setNumberRange(0, chartData.length);
          var colors = [];
          $.each(chartData, function (index) {
            colors.push('#' + rainbow.colourAt(index));
          });

          responseContentTypeDonutChart.options.colors = colors;
          responseContentTypeDonutChart.setData(chartData);
        } else {
          responseContentTypeDonutChart.setData([{label: 'No data', value: 0}]);
        }
      };

      var updateTopUris = function (data) {
        var html = '';
        var topUris = data.aggregations.top_uris.buckets;
        $.each(topUris, function (index, topUri) {
          var item = {label: topUri.key, value: topUri.doc_count};
          html += '<tr><td>' + topUri.key + '</td><td>' + topUri.doc_count + '</td></tr>'
        });
        $("#top_uris table tbody").html(html);
      };

      var updateFlopUris = function (data) {
        var html = '';
        var flopUris = data.aggregations.flop_uris.buckets;
        $.each(flopUris, function (index, flopUri) {
          var item = {label: flopUri.key, value: flopUri.doc_count};
          html += '<tr><td>' + flopUri.key + '</td><td>' + flopUri.doc_count + '</td></tr>'
        });
        $("#flop_uris table tbody").html(html);
      };

      var currentPeriod = 'PAST_WEEK';
      $("[data-toggle='period']").click(function () {
        var buttons = $("[data-toggle='period']")
        buttons.removeClass("btn-primary");
        buttons.addClass("btn-default");

        var current = $(this);
        current.removeClass("btn-default");
        current.addClass("btn-primary");

        currentPeriod = $(this).data("period");
        updateData();
      });

      var updateData = function () {
        $(document).find("#charts .ibox-content").toggleClass("sk-loading");
        $.get("/blossom/actuator/tracesstats?period=" + currentPeriod, function (data) {
          updateRequests(data);
          updateResponseTime(data);
          updateResponseStatus(data);
          updateResponseContentType(data);
          updateTopUris(data);
          updateFlopUris(data);

          $(document).find("#charts .ibox-content").toggleClass("sk-loading");
        });
      };

      setInterval(updateData, 10000);
      updateData();
    }
  );
</script>

blossom-ui/blossom-ui-web/src/main/resources/templates/blossom/system/dashboard/panel/memory.ftl
<#import "/spring.ftl" as spring>

<div id="memory" class="ibox float-e-margins">
  <div class="ibox-title">
    <h5><@spring.message "dashboard.jvm.memory"/></h5>
  </div>
  <div class="ibox-content">
    <div class="sk-spinner sk-spinner-wave">
      <div class="sk-rect1"></div>
      <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
      <div class="sk-rect4"></div>
      <div class="sk-rect5"></div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <ul class="stat-list">
          <li>
            <h2 class="no-margins">${memory.jvm.percentage?string[".0"]}%</h2>
            <small><@spring.message "dashboard.jvm.memory.global"/></small>
            <div class="stat-percent small"><@spring.message "dashboard.jvm.memory.used"/>
              : ${memory.jvm.used} / <@spring.message "dashboard.jvm.memory.total"/>
              : ${memory.jvm.total}</div>
            <div class="progress progress-mini">
              <div style="width:${memory.jvm.percentage?c}%" class="progress-bar"></div>
            </div>
          </li>
          <li>
            <h2 class="no-margins ">${memory.heap.percentage?string[".0"]}%</h2>
            <small><@spring.message "dashboard.jvm.memory.heap"/></small>
            <div class="stat-percent small"><@spring.message "dashboard.jvm.memory.used"/>
              : ${memory.heap.used} / <@spring.message "dashboard.jvm.memory.committed"/>
              : ${memory.heap.committed} / <@spring.message "dashboard.jvm.memory.max"/>
              : ${memory.heap.max}</div>
            <div class="progress progress-mini">
              <div style="width: ${memory.heap.percentage?c}%" class="progress-bar"></div>
            </div>
          </li>
          <li>
            <h2 class="no-margins ">${memory.nonheap.percentage?string[".0"]}%</h2>
            <small><@spring.message "dashboard.jvm.memory.nonheap"/></small>
            <div class="stat-percent small"><@spring.message "dashboard.jvm.memory.used"/>
              : ${memory.nonheap.used} / <@spring.message "dashboard.jvm.memory.committed"/>
              : ${memory.nonheap.committed} / <@spring.message "dashboard.jvm.memory.max"/>
              : ${memory.nonheap.max}</div>
            <div class="progress progress-mini">
              <div style="width: ${memory.nonheap.percentage?c}%" class="progress-bar"></div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

blossom-ui/blossom-ui-web/src/main/resources/templates/blossom/system/dashboard/panel/status.ftl
<#import "/spring.ftl" as spring>

<div id="status" class="ibox float-e-margins">
  <div class="ibox-title">
    <h5><@spring.message "dashboard.server.status" /></h5>
    <div class="ibox-tools">
      <span class="label label-primary pull-right"></span>
    </div>
  </div>
  <div class="ibox-content">
    <div class="sk-spinner sk-spinner-wave">
      <div class="sk-rect1"></div>
      <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
      <div class="sk-rect4"></div>
      <div class="sk-rect5"></div>
    </div>

    <h2 class="global <#if health.getStatus().getCode() == 'UP'>text-navy<#else>text-danger</#if>">
      <i class="fa fa-play <#if health.getStatus().getCode() == 'UP'>fa-rotate-270<#else>fa-rotate-90</#if>"></i>
      <@spring.messageText "dashboard.server.status."+health.getStatus().getCode() health.getStatus().getCode() />
    </h2>

    <table class="table table-stripped small m-t-md">
      <tbody>
      <#list health.getDetails()?keys as key>
      <tr>
        <td
          class="<#if health.getDetails()[key].getStatus().getCode() == 'UP'>text-navy<#else>text-danger</#if>">
          <i class="fa fa-play <#if health.getDetails()[key].getStatus().getCode() == 'UP'>fa-rotate-270<#else>fa-rotate-90</#if>"></i>
          <@spring.messageText "dashboard.server.status."+health.getDetails()[key].getStatus().getCode() health.getDetails()[key].getStatus().getCode() />
        </td>
        <td>
        ${key}
        </td>

        <td>
          <#assign details = health.getDetails()[key].getDetails()/>
          <#if details??>
            <i class="fa fa-question-circle text-navy"
               data-toggle="popover"
               data-trigger="hover"
               data-html="true"
               data-container="body"
               data-placement="auto"
               data-content="<ul class='unstyled'><#list details?keys as detailKey><li><div><strong>${detailKey} :</strong> ${details[detailKey]}</li></#list></div></ul>">
            </i>
          </#if>
        </td>
      </tr>
      </#list>
      </tbody>
    </table>
  </div>
</div>

<script>
  $(document).ready(function () {
    $("#status .ibox-tools .label").text(moment.duration(${uptime?c}).humanize());
    $("#status [data-toggle='popover']").popover();
  });
</script>